# Colores para estilos
CSI = "\033["
BLUE = CSI + "94m"
RED = CSI + "91m"
WHITE = CSI + "97m"
CYAN = CSI + "96m"
BOLD = CSI + "1m"
PINK = CSI + "95m"
PURPLE = CSI + "35m"
LIGHT_GREEN = CSI + "92m"
LIME = CSI + "92m"             
GOLD = CSI + "33m"        
ORANGE = CSI + "38;5;208m"
RESET = CSI + "0m"